/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BriefingRouteImport } from './routes/briefing'
import { Route as ClaimClaimIdRouteImport } from './routes/claim.$claimId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingRoute = BriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimClaimIdRoute = ClaimClaimIdRouteImport.update({
  id: '/claim/$claimId',
  path: '/claim/$claimId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/briefing': typeof BriefingRoute
  '/claim/$claimId': typeof ClaimClaimIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/briefing': typeof BriefingRoute
  '/claim/$claimId': typeof ClaimClaimIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/briefing': typeof BriefingRoute
  '/claim/$claimId': typeof ClaimClaimIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/briefing' | '/claim/$claimId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/briefing' | '/claim/$claimId'
  id: '__root__' | '/' | '/briefing' | '/claim/$claimId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BriefingRoute: typeof BriefingRoute
  ClaimClaimIdRoute: typeof ClaimClaimIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing': {
      id: '/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof BriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$claimId': {
      id: '/claim/$claimId'
      path: '/claim/$claimId'
      fullPath: '/claim/$claimId'
      preLoaderRoute: typeof ClaimClaimIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BriefingRoute: BriefingRoute,
  ClaimClaimIdRoute: ClaimClaimIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
